### ISSUE TITLE
请问有加入sendcloud api的打算吗

### ISSUE THREAD

**Issue by moqiaoduo** [esdeathlove/ss-panel-v3-mod#542]
我觉得这个有点用处，不过我不大会改php尤其是加入sdk，望能加入

**Comment by CherishUUU** [comment]
恩恩，支持sendcloud，求加入~~QQ邮箱经常被退回回

**Comment by csbde** [comment]
我做了sendcloud 支持，但我的整个结构都改变了，所以无法合并到这边了

**Comment by atrong** [comment]
测试成功

**Comment by moqiaoduo** [comment]
感谢，测试成功了，我是加入修改的地方的

**Comment by moqiaoduo** [comment]
@csbde 发送的邮件没有带附件（每日备份），这个可以解决吗

**Comment by Woophp** [comment]
@csbde  感谢，测试好用，QQ邮箱秒收，同楼上发现没有备份附件的问题。

**Comment by Woophp** [comment]
@csbde   自己参照Sendcloud文档改了改，可以正常发附件了，再次感谢。

**Comment by tang1989324** [comment]
@Woophp @csbde  service 增加这个在哪添加？

**Comment by Woophp** [comment]
自己新建一个文件App\Services\Mail\Sendcloud.php

2017年4月21日 13:27，"tang1989324" <notifications@github.com>写道：

@Woophp <https://github.com/Woophp> @csbde <https://github.com/csbde>
service 增加这个在哪添加？

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/esdeathlove/ss-panel-v3-mod/issues/542#issuecomment-296072830>,
or mute the thread

**Comment by tang1989324** [comment]
@Woophp 好的 感谢$API_USER = $this->config['api_user'];
		$API_KEY = $this->config['key']; 替换[]里面两个是吧

**Comment by tang1989324** [comment]
@Woophp弄好了然后还要改什么才能发验证码和到期前邮件通知？

**Comment by Woophp** [comment]
@tang1989324 怎么发发验证码和到期前邮件通知根这个没关系啊，这个是自行加入了sendcloud支持

**Comment by tang1989324** [comment]
@那我设置好了没有发邮件 在sendcloud上发测试邮件OK的  是哪里不对吗$API_USER = $this->config['api_user'];
$API_KEY = $this->config['key']; 替换[]里面两个

**Comment by tang1989324** [comment]
@Woophp附件要怎么修改的？自动备份邮件没有附件？哪里要改下

**Comment by tang1989324** [comment]
@Woophp 哥们 在了吗 每日备份的邮件请指教下 拜托了

**Comment by Woophp** [comment]
你要自己改sendcloud.php，参照sendcloud的官方文档

**Comment by tang1989324** [comment]
@Woophp 这个我知道，可是实在不会改 = =求你发一下改好的 跟楼上一样 拜托了

**Comment by tang1989324** [comment]
用了这个之后到期邮件和账号删除提现邮件都不发送的？
